### ISSUE TITLE
Compute the energy

### ISSUE THREAD

**Issue by dlezcano** [baylibre-acme/pyacmegraph#4]
Hi Sebastien,

it would be really nice if the accumulated energy could be displayed and also could be retrieved from command line (start stop get).

 -- Daniel

**Comment by sebjan** [comment]
Hi Daniel,

While testing and reviewing the code, I realize that the currently reported energy information is the accumulated energy over the zoom-window time-frame (while the UI indicates 'mean' energy). The accumulated energy is actually the information I wanted to retrieve, so I'll fix the UI title to reflect the implementation.
Do you see a need for a 'mean energy' information?

Regarding the command-line feature, it is not the way the tool is implemented now: it can take parameters at startup, but not during runtime. It would be easy to add a periodic reporting of the accumulated energy (either through a dedicated option, or through a debug trace level), for example to report each 5s the accumulated energy visible in the zoom-window. Would this help?

An idea for handling command lines on top of current implementation would be to make pyacmegraph act as a server (handling IIO connection, UI, data storage, ...) and use another instance of (client) pyacmegraph to just send commands to the server instance...

Seb

**Comment by sebjan** [comment]
Just pushed commit:
dbf3b665c fix energy computation naming (to Accumulated Energy)
to fix the UI and indicate 'Accumulated energy' instead of 'Mean Energy' which was wrong.

I'll close this issue, and created another one https://github.com/baylibre-acme/pyacmegraph/issues/5 for tracking a more generic 'control pyacmegraph from command line'.
